version: '3.8'  # Add this version line

services:
  db:
    build: .
    container_name: pg_keyjwt
    restart: always
    environment:
      POSTGRES_USER: tota
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: projectdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: tota
      KC_DB_PASSWORD: 123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8180:8080"
    depends_on:
      - db
    command: start-dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: